### ISSUE TITLE
Feature Request:  Using Logrx with Rmd files

### ISSUE THREAD

**Issue by bms63** [pharmaverse/logrx#140]
### Feature Idea

 Create Unit Test for Rmd files

**Comment by nicholas-masel** [comment]
@bms63  I'm very interested in what this one about?  Is this just a pass/fail that they run w/out error or a snapshot test, so we catch issues with the Rmd sooner?

**Comment by bms63** [comment]
Yeah just a simple test to make sure `.Rmd` files work with logrx.  I'm assuming they do, but honestly I have not checked.  Once we check the all is running well it would be nice to say that the package works with `.Rmd` as well as `.R` files! :)

**Comment by nicholas-masel** [comment]
@bms63 @kodesiba   I just tried this out and it fails.

```r
> axecute("test.Rmd")
Error: attempt to use zero-length variable name
```

This has quickly become a priority :)  I'll dig in a bit and see what I come up with here.

This is how we would want to call this right, and logrx would just need to recognize it's a markdown file and knit it?

**Comment by nicholas-masel** [comment]
I think we can swap in `rmarkdown::render()` instead of `source()` right here: https://github.com/pharmaverse/logrx/blob/ef8428e7072a55f7b80b3287766143ba673b7a38/R/interact.R#L121

**Comment by nicholas-masel** [comment]
> Perhaps we could just extract the relevant R code and execute it?

Yep! We can do this to get the used functions. Turns out `parse()` doesn't work for Rmd.

**Comment by nicholas-masel** [comment]
It needs work still, but I've got a version where it will render now and errors are logged.  Function use is also an issue here, since functions like `knitr::opts_chunk$set(echo = TRUE)` are not captured cleanly.

**Comment by bms63** [comment]
What happens when they in line R code versus knitr chunks

**Comment by nicholas-masel** [comment]
Ok, so logrx checks each package for objects in their environment and returns those that are functions.  If an object is a list it does not return it.  An object in a package can be a list of functions.  This is the case with `knitr::opts_chunk`.

My thought was to search lists for functions and include these when trying to link a function to a package.  Nope. It is designed this way since there are multiple `get()`, for example `knitr::opts_chunk$get()` and `knitr::opts_current$get()`.

To be able to check this, we would need to sort out how to keep the list object with the function when parsing to be able to distinguish between `knitr::opts_chunk$get()` and `knitr::opts_current$get()`.
