### ISSUE TITLE
Bug: A blank line is required at end of file

### ISSUE THREAD

**Issue by nicholas-masel** [pharmaverse/logrx#159]
### What happened?

Running any file that doesn't end with a blank line give you this warning:

```r
Warning in readLines(file) :
  incomplete final line found on 'a/path/to/file.R'
```
Should we turn off the warning in `readLines()`?
https://github.com/pharmaverse/logrx/blob/ef8428e7072a55f7b80b3287766143ba673b7a38/R/interact.R#L142

### Session Information

NA

### Reproducible Example

NA

**Comment by bms63** [comment]
Isn't it best practice to end a file with a new line?  

I'm happy to turn it off just to make it easier!

**Comment by parmsam-pfizer** [comment]
Ran into this error too. I agree with it being best practice. It lines up with {lintr}. Maybe the message could be updated to resemble what lintr uses so it's clearer. Example of that: "Line 5 [trailing_blank_lines_linter] Missing terminal newline." Alternatively, maybe this sort of static code analysis in this package could be made optional to the user. lintr could be an optional dependency (suggest) in the package with a new argument in axecute to also lint the source file, since it has a lot of these checks built in already.
