### ISSUE TITLE
`cyclocomp` via `lintr` installs `remotes`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/logrx#202]
Hey all,

In GSK's review of `logrx` they discovered that `cyclocomp` is installing the `remotes` package.    @nicholas-masel are you familiar with `cyclocomp` and why it needs the remotes package?  We were looking to not have our frozen environments users access to packages like `remotes` as even if we block access to public interfaces, backdoors are always found by crafty users!

Not sure if there is anything we can do about this in the end, but something to think about as maybe other organizations might be nervous to use logrx in frozen-like environments.

@pharmaverse/logrx thoughts??

**Comment by nicholas-masel** [comment]
There is a lint in `lintr` for complex code that is using `cyclocomp`.

`cyclocomp` is using [`remotes::install_local()`](https://github.com/MangoTheCat/cyclocomp/blob/8ac6139b3c8ffd4fdb4941a6d94c6d34a848e6ea/R/package_dir.R#L11).

So it isn't using anything to access external interfaces here.  I'm open to doing what we need to remove the remotes dependency.

**Comment by thebioengineer** [comment]
In general, it might be a good idea to make it so the users can turn off/on different elements of logging, rather than always doing them. 

https://github.com/pharmaverse/logrx/blob/678a34c4600c61d10bbcf512cbf0592bea395505/R/log.R#L110

Just based on this line, you could update log config to have an argument where the user can set which elements they would like to capture. with "keys" being hardcoded within the function, it really isn't config-ing in the user sense.

**Comment by nicholas-masel** [comment]
@bms63 @thebioengineer   Do we need to have lintr as a suggests for you to be able to use this in your frozen environment?  Or have the dependency completely removed?

**Comment by thebioengineer** [comment]
I talked with Ben the other day, I think moving lintr into suggests is just a better location for it generally since it's not core functionality. Then throw a check that the package is installed before trying to call lintr in the get_lint_results function

**Comment by nicholas-masel** [comment]
Gotcha, that should work.  We meet Monday and will chat about it with the group.  This should be doable though for this release.
